spring:
  application:
    name : spring-gift
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
